from typing import List

STANDARD_CRD_HEADERS_56 = [
    "CONTROL_NUMBER",                                  # 1
    "TITLE",                                           # 2
    "FIRST_NAME",                                      # 3
    "MIDDLE_NAME",                                     # 4
    "LAST_NAME",                                       # 5
    "SUFFIX",                                          # 6
    "SALUTATION",                                      # 7
    "ATTENTION_1",                                     # 8
    "ATTENTION_2",                                     # 9
    "STREET",                                          # 10
    "CITY",                                            # 11
    "STATE",                                           # 12
    "ZIP_CODE",                                        # 13
    "COUNTRY",                                         # 14
    "PHONE",                                           # 15
    "EMAIL",                                           # 16
    "STATUS_CODES",                                    # 17
    "CLIENT_#",                                        # 18
    "OPERATOR_#",                                      # 19
    "DATE_OF_CALL_MMDDYY",                             # 20
    "TIME_OF_CALL_hhMMSS_24HOUR_CLOCK",                # 21
    "CALL_TYPE_INFORMATION_PRODUCT_REFERRAL_CUSTSVC_HANGUPPRANK",  # 22
    "CALL_LETTERS_MEDIA_SOURCE",                       # 23
    "COMMENTS",                                        # 24
    "SHIP_TO_NAME",                                    # 25
    "SHIP_TO_STREET",                                  # 26
    "SHIP_TO_ATTN_1",                                  # 27
    "SHIP_TO_ATTN_2",                                  # 28
    "SHIP_TO_CITY",                                    # 29
    "SHIP_TO_STATE",                                   # 30
    "SHIP_TO_ZIP",                                     # 31
    "SHIP_TO_COUNTRY",                                 # 32
    "ORDER_TERMS_CC_CASH_COD_ECT",                     # 33
    "SHIP_MODE_UPS_FEDEX_ETC",                         # 34
    "CREDITE_CARD_TYPE_VISA_MASTERCARD_AMEX_DISCOVER", # 35
    "CREDIT_CARD_NUMBER",                              # 36
    "CREDIT_CARD_EXPIRATION_DATE_MM_SLASH_YY",         # 37
    "CREDIT_CARD_SECURTITY_CODE",                      # 38
    "CREDIT_CARD_HOLDER_FULLNAME",                     # 39
    "ELEC_CHECKING_BANKING_ROUTING_#",                 # 40
    "ELEC_CHECKING_ACCOUNT_#",                         # 41
    "ELEC_CHECKING_CHEDCK_#",                          # 42
    "ORDER_TOTAL_0000_DOT_00",                         # 43
    "ITEM_COUNT",                                      # 44
    "CREDIT_CARD_PROCESSING_STATUS_CLEARED_OR_DECLINED", # 45
    "AMOUNT_CLEARED",                                  # 46
    "TRANSACTION_DATE_DATE_CARD_CLEARED_OR_WAS_DOUBLE_DECLINED", # 47
    "ITEM",                                            # 48
    "DESCRIPTION",                                     # 49
    "QUANTITY",                                        # 50
    "UNIT_RETAIL",                                     # 51
    "GROSS_PRICE_UNIT_RETAIL_TIMES_QUANTITY",          # 52
    "DISCOUNT",                                        # 53
    "SALES_TAX",                                       # 54
    "NET_PRICE_GROSS_MINUS_DISCOUNT_PLUS_SALES_TAX",   # 55
    "UNUSED_TRAILING_FIELD",                           # 56
]

EXTENDED_CRD_HEADERS_64 = [
    "CONTROL_NUMBER",                                  # 1
    "TITLE",                                           # 2
    "FIRST_NAME",                                      # 3
    "MIDDLE_NAME",                                     # 4
    "LAST_NAME",                                       # 5
    "SUFFIX",                                          # 6
    "SALUTATION",                                      # 7
    "ATTENTION_1",                                     # 8
    "ATTENTION_2",                                     # 9
    "STREET",                                          # 10
    "CITY",                                            # 11
    "STATE",                                           # 12
    "ZIP_CODE",                                        # 13
    "COUNTRY",                                         # 14
    "PHONE",                                           # 15
    "EMAIL",                                           # 16
    "STATUS_CODES",                                    # 17
    "CLIENT_#",                                        # 18
    "OPERATOR_#",                                      # 19
    "DATE_OF_CALL_MMDDYY",                             # 20
    "TIME_OF_CALL_hhMMSS_24HOUR_CLOCK",                # 21
    "CALL_TYPE_INFORMATION_PRODUCT_REFERRAL_CUSTSVC_HANGUPPRANK",  # 22
    "CALL_LETTERS_MEDIA_SOURCE",                       # 23
    "COMMENTS",                                        # 24
    "SHIP_TO_NAME",                                    # 25
    "SHIP_TO_STREET",                                  # 26
    "SHIP_TO_ATTN_1",                                  # 27
    "SHIP_TO_ATTN_2",                                  # 28
    "SHIP_TO_CITY",                                    # 29
    "SHIP_TO_STATE",                                   # 30
    "SHIP_TO_ZIP",                                     # 31
    "SHIP_TO_COUNTRY",                                 # 32
    "ORDER_TERMS_CC_CASH_COD_ECT",                     # 33
    "SHIP_MODE_UPS_FEDEX_ETC",                         # 34
    "CREDITE_CARD_TYPE_VISA_MASTERCARD_AMEX_DISCOVER", # 35
    "CREDIT_CARD_NUMBER",                              # 36
    "CREDIT_CARD_EXPIRATION_DATE_MM_SLASH_YY",         # 37
    "CREDIT_CARD_SECURTITY_CODE",                      # 38
    "CREDIT_CARD_HOLDER_FULLNAME",                     # 39
    "ELEC_CHECKING_BANKING_ROUTING_#",                 # 40
    "ELEC_CHECKING_ACCOUNT_#",                         # 41
    "ELEC_CHECKING_CHEDCK_#",                          # 42
    "ORDER_TOTAL_0000_DOT_00",                         # 43
    "ITEM_COUNT",                                      # 44
    "CREDIT_CARD_PROCESSING_STATUS_CLEARED_OR_DECLINED", # 45
    "AMOUNT_CLEARED",                                  # 46
    "TRANSACTION_DATE_DATE_CARD_CLEARED_OR_WAS_DOUBLE_DECLINED", # 47
    "ITEM",                                            # 48
    "DESCRIPTION",                                     # 49
    "QUANTITY",                                        # 50
    "UNIT_RETAIL",                                     # 51
    "GROSS_PRICE_UNIT_RETAIL_TIMES_QUANTITY",          # 52
    "DISCOUNT",                                        # 53
    "SALES_TAX",                                       # 54
    "NET_PRICE_GROSS_MINUS_DISCOUNT_PLUS_SALES_TAX",   # 55

    "ITEM_2",                                          # 56
    "DESCRIPTION_2",                                   # 57
    "QUANTITY_2",                                      # 58
    "UNIT_RETAIL_2",                                   # 59
    "GROSS_PRICE_UNIT_RETAIL_TIMES_QUANTITY_2",        # 60
    "DISCOUNT_2",                                      # 61
    "SALES_TAX_2",                                     # 62
    "NET_PRICE_GROSS_MINUS_DISCOUNT_PLUS_SALES_TAX_2", # 63

    "UNUSED_TRAILING_FIELD",                           # 64
]
